# onnx_path: "kungfu_0609.onnx"
# motion_length: 17.433

onnx_path: "taichi.onnx"
motion_length: 6.967

# onnx_path: "throw_arms_149000.onnx"
# onnx_path: "throw_arms_400000.onnx"
# motion_length: 12.667

kps: [100, 100, 100, 150, 40, 40,
      100, 100, 100, 150, 40, 40,
      400, 400, 400,
      100, 100,  50, 50, 10, 10, 10,
      100, 100,  50, 50, 10, 10, 10
      ]

kds: [2, 2, 2, 4, 2, 2,
      2, 2, 2, 4, 2, 2,
      5.0, 5.0, 5.0,
      2, 2, 2, 2, 0.1, 0.1, 0.1,
      2, 2, 2, 2, 0.1, 0.1, 0.1
      ]

tau_limit: [88, 88, 88, 139, 50, 50,
            88, 88, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 5, 5, 5,
            25, 25, 25, 25, 5, 5, 5
           ]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                 -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                  0.0, 0.0, 0.0,
                  0.2, 0.2, 0.0, 0.9, 0.0, 0.0, 0.0, 
                  0.2, -0.2, 0.0, 0.9, 0.0, 0.0, 0.0
                  ]

dof23_index: [ 0, 1, 2, 3, 4, 5,
               6, 7, 8 ,9 ,10, 11,
               12, 13, 14,
               15, 16, 17, 18,
               22, 23, 24, 25
             ]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
history_length: 4
num_actions: 23
num_obs: 380

##########################################################
############### Locomotion部分 ##########################
##########################################################

policy_path_loco: "policy_29dof.pt"

kps_loco: [200, 200, 200,
      150, 150, 200,
      150, 150, 200,
      200, 200,      100, 100,
      20,  20,       100, 100,
      20,  20,       50,  50, 
                  50,  50,
                  40,  40,
                  40,  40,
                  40,  40]

kds_loco: [5, 5, 5, 
      5, 5, 5, 
      5, 5, 5, 
      5, 5,     2, 2,
      2, 2,     2, 2, 
      2, 2,     2, 2,
                2, 2,
                2, 2,
                2, 2,
                2, 2]

tau_limit_loco: [88, 88, 88, 139, 50, 50,
            88, 88, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 5, 5, 5,
            25, 25, 25, 25, 5, 5, 5
           ]
default_angles_loco: [-0.2,  -0.2,  0.0,
                  0.0,   0.0,  0.0,
                  0.0,   0.0,  0.0, 
                  0.42,  0.42,       0.35,  0.35,
                 -0.23, -0.23,       0.18, -0.18, 
                  0.0,   0.0,        0.0,   0.0, 
                                     0.87,  0.87, 
                                     0.0,   0.0, 
                                     0.0,   0.0, 
                                     0.0,   0.0]
joint2motor_idx: [0, 6, 12, 
                  1, 7, 13, 
                  2, 8, 14, 
                  3, 9,      15, 22,
                  4, 10,     16, 23, 
                  5, 11,     17, 24, 
                             18, 25, 
                             19, 26, 
                             20, 27, 
                             21, 28]
cmd_scale_loco: [1.0, 1.0, 1.0]
cmd_init_loco: [0, 0, 0]

ang_vel_scale_loco: 1.0
dof_pos_scale_loco: 1.0
dof_vel_scale_loco: 1.0
action_scale_loco: 0.25
num_actions_loco: 29
num_obs_loco: 96
cmd_range_loco: {lin_vel_x: [-0.4, 0.7], lin_vel_y: [-0.4, 0.4], ang_vel_z: [-1.57, 1.57]}